source("local_library.R", local = TRUE)
use_vald_local_library()
source('R/roster_trackman.R')
source('R/player_health.R')
library(testthat)
test_that('ArmCare keeps history across exports and newer corrections replace overlapping exams',{
  root<-tempfile('armcare-history-');dir.create(root);on.exit(unlink(root,recursive=TRUE))
  old<-data.frame('First Name'='Cade','Last Name'='Smith','Exam Date'=c('09/01/2025','09/02/2025'),Time='10:00:00','Exam Type'='Fresh - Quick','Arm Score'=c(70,80),check.names=FALSE)
  new<-old[2,,drop=FALSE];new[['Arm Score']]<-85
  post<-new;post[['Exam Type']]<-'Post';post[['Arm Score']]<-NA
  iso<-new;iso[['Exam Date']]<-'2026-09-01'
  write.csv(old,file.path(root,'Daily Log old.csv'),row.names=FALSE)
  write.csv(rbind(new,post,iso),file.path(root,'Daily Log new.csv'),row.names=FALSE)
  Sys.setFileTime(file.path(root,'Daily Log old.csv'),Sys.time()-100)
  h<-health_read(root)
  expect_equal(nrow(h$fresh),3)
  expect_equal(nrow(h$post),1)
  expect_equal(nrow(h$exams),4)
  expect_equal(as.numeric(h$fresh[['Arm Score']][h$fresh$date==as.Date('2025-09-02')]),85)
  expect_equal(min(h$fresh$date),as.Date('2025-09-01'))
  expect_equal(max(h$fresh$date),as.Date('2026-09-01'))
  expect_match(attr(h$fresh,'source'),'Daily Log old.csv',fixed=TRUE)
  expect_false(any(grepl('fresh|post|exams',h$errors)))
})
test_that('empty exam types and missing times preserve valid records',{
  root<-tempfile('armcare-history-');dir.create(root);on.exit(unlink(root,recursive=TRUE))
  d<-data.frame('First Name'='Cade','Last Name'='Smith','Exam Date'='09/01/2025',Time=NA_character_,'Exam Type'='Fresh - Quick','Arm Score'=c(70,80),check.names=FALSE)
  write.csv(d,file.path(root,'Daily Log one.csv'),row.names=FALSE)
  write.csv(d,file.path(root,'Daily Log two.csv'),row.names=FALSE)
  h<-health_read(root)
  expect_equal(nrow(h$fresh),2)
  expect_equal(nrow(h$post),0)
  expect_false(any(grepl('fresh|post|exams',h$errors)))
})
