source("local_library.R", local = TRUE)
use_vald_local_library()
Sys.setenv(VALD_AUTO_REFRESH="false",VALD_REFRESH_WORKER="true")
source("dashboard.R")
library(testthat)
d <- health_read()
stopifnot(!length(d$errors), nrow(d$fresh)>0, nrow(d$events)>0)
test_that("latest selection is chronological and missing workload stays missing", {
  x<-data.frame(key=c("a","a"),date=as.Date(c("2026-09-01","2026-09-02")),order=1:2)
  expect_equal(health_latest(x)$date,as.Date("2026-09-02"))
  expect_true(any(is.na(d$workload[["One Day Workload"]])))
  expect_equal(health_key("  Sam Hall  "),"sam hall")
})
shiny::testServer(function(input,output,session) health_server(input,output,session,reactive(data.frame()),reactive(data.frame())), {
  session$setInputs(hc_arm_player="titan targac",hc_arm_dates=as.Date(c("2026-08-01","2026-09-24")),hc_arm_mode="fresh",hc_exam_type="Fresh",hc_exam_measure="strength",hc_pulse_player="jonathan anders",hc_pulse_dates=as.Date(c("2026-08-01","2026-09-24")),hc_calendar_month=as.Date("2026-09-01"),hc_throw_date="2026-09-16",hc_throw_metrics=c("torque","armSpeed"),hc_combined_player="jonathan anders")
  for(n in c("hc_arm_metrics","hc_arm_exams","hc_arm_summary","hc_arm_trend","hc_pulse_team","hc_workload_plot","hc_chronic_plot","hc_calendar","hc_throw_cards","hc_throw_plot","hc_combined_table","hc_pulse_trend")) expect_no_error(output[[n]])
  session$setInputs(hc_arm_mode="post",hc_exam_measure="rom",hc_high_effort=TRUE)
  expect_no_error(output$hc_arm_metrics)
  expect_no_error(output$hc_arm_exams)
  expect_no_error(output$hc_throw_plot)
  session$setInputs(hc_arm_player="")
  expect_no_error(output$hc_arm_trend)
})
cat("Health source and reactive checks passed.\n")
