source("local_library.R", local = TRUE)
use_vald_local_library()
library(testthat)
root<-tempfile('refresh-state-');dir.create(root)
Sys.setenv(VALD_APP_ROOT=root,VALD_REFRESH_WORKER='true',VALD_AUTO_REFRESH='false')
source('runtime/refresh_runtime.R')
shared_data<-new.env()
test_that('a truncated status preserves cached timestamps and recovers on the next valid read',{
  now<-Sys.time()
  state<-list(message='Ready',attempted=now,success=now,ok=TRUE)
  atomic_rds(state,state_file)
  expect_identical(read_refresh_state(),state)
  writeBin(as.raw(c(31,139)),state_file)
  expect_no_warning(fallback<-read_refresh_state())
  expect_equal(fallback$success,now)
  expect_equal(fallback$attempted,now)
  expect_match(fallback$message,'could not be read')
  expect_false(refresh_due(fallback))
  expect_no_error(shiny::isolate(poll_refresh()))
  state$message<-'Recovered';state$success<-now+1
  atomic_rds(state,state_file)
  expect_identical(read_refresh_state(),state)
  expect_no_error(shiny::isolate(poll_refresh()))
  expect_equal(shiny::isolate(refresh_message()),'Recovered')
})
test_that('cold-start corruption and invalid status schemas do not break polling',{
  state_file<<-file.path(refresh_dir,'cold-status.rds')
  writeBin(raw(),state_file)
  s<-read_refresh_state()
  expect_true(is.na(s$success));expect_false(refresh_due(s))
  expect_identical(read_refresh_state()$attempted,s$attempted)
  expect_true(refresh_due(s,now=s$attempted+3601))
  expect_no_error(shiny::isolate(poll_refresh()))
  atomic_rds(list(message='Bad date',attempted='invalid'),state_file)
  expect_match(read_refresh_state()$message,'could not be read')
  atomic_rds('not a state list',state_file)
  expect_match(read_refresh_state()$message,'could not be read')
})
test_that('a missing status on first launch still permits the initial refresh',{
  state_file<<-file.path(refresh_dir,'new-status.rds')
  expect_equal(read_refresh_state()$message,'Not refreshed yet')
  expect_true(refresh_due(read_refresh_state()))
})
unlink(root,recursive=TRUE)
